## tidyr

In [9]:
# Instalando o pacote
# install.packages('tidyr')

# Carregando o pacote
library(tidyr)
library(ggplot2)
library(dplyr)

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

In [5]:
data('economics')

In [6]:
?economics

In [7]:
head(economics)

  date       pce   pop    psavert uempmed unemploy
1 1967-07-01 506.7 198712 12.6    4.5     2944
2 1967-08-01 509.8 198911 12.6    4.7     2945
3 1967-09-01 515.6 199113 11.9    4.6     2958
4 1967-10-01 512.2 199311 12.9    4.9     3143
5 1967-11-01 517.4 199498 12.8    4.7     3066
6 1967-12-01 525.1 199657 11.8    4.8     3018

In [10]:
economics  %>% 
    # criar nova variável com o ano da data
    mutate(ano = lubridate::year(date))  %>% 
    # agrupar os dados por ano
    group_by(ano)  %>% 
    # calcular as medias de todas as variáveis
    summarise(
    pce = mean(pce),
    pop = mean(pop),
    psavert = mean(psavert),
    uempmed = mean(uempmed),
    unemploy = mean(unemploy)
    )  %>% 
    head()

  ano  pce      pop      psavert  uempmed  unemploy
1 1967 514.4667 199200.3 12.43333 4.700000 3012.333
2 1968 556.8417 200663.8 11.33333 4.500000 2797.417
3 1969 603.6500 202648.7 10.90000 4.441667 2830.167
4 1970 646.7250 204982.3 12.80000 4.983333 4127.333
5 1971 699.9250 207589.3 13.47500 6.275000 5021.667
6 1972 768.1500 209837.6 12.35000 6.108333 4875.833

In [11]:
# tranformando o dataset em long
economics  %>% 
    gather(indicador, valor, -date)

     date       indicador valor
1    1967-07-01 pce       506.7
2    1967-08-01 pce       509.8
3    1967-09-01 pce       515.6
4    1967-10-01 pce       512.2
5    1967-11-01 pce       517.4
6    1967-12-01 pce       525.1
7    1968-01-01 pce       530.9
8    1968-02-01 pce       533.6
9    1968-03-01 pce       544.3
10   1968-04-01 pce       544.0
11   1968-05-01 pce       549.8
12   1968-06-01 pce       556.3
13   1968-07-01 pce       563.2
14   1968-08-01 pce       567.0
15   1968-09-01 pce       568.2
16   1968-10-01 pce       571.6
17   1968-11-01 pce       576.7
18   1968-12-01 pce       576.5
19   1969-01-01 pce       583.5
20   1969-02-01 pce       588.7
21   1969-03-01 pce       588.9
22   1969-04-01 pce       593.9
23   1969-05-01 pce       600.3
24   1969-06-01 pce       600.9
25   1969-07-01 pce       602.7
26   1969-08-01 pce       609.9
27   1969-09-01 pce       613.2
28   1969-10-01 pce       618.5
29   1969-11-01 pce       620.5
30   1969-12-01 pce       622.8
...  ...        ...       ...
2841 2012-11-01 unemploy  12005
2842 2012-12-01 unemploy  12298
2843 2013-01-01 unemploy  12471
2844 2013-02-01 unemploy  11950
2845 2013-03-01 unemploy  11689
2846 2013-04-01 unemploy  11760
2847 2013-05-01 unemploy  11654
2848 2013-06-01 unemploy  11751
2849 2013-07-01 unemploy  11335
2850 2013-08-01 unemploy  11279
2851 2013-09-01 unemploy  11270
2852 2013-10-01 unemploy  11136
2853 2013-11-01 unemploy  10787
2854 2013-12-01 unemploy  10404
2855 2014-01-01 unemploy  10202
2856 2014-02-01 unemploy  10349
2857 2014-03-01 unemploy  10380
2858 2014-04-01 unemploy   9702
2859 2014-05-01 unemploy   9859
2860 2014-06-01 unemploy   9460
2861 2014-07-01 unemploy   9608
2862 2014-08-01 unemploy   9599
2863 2014-09-01 unemploy   9262
2864 2014-10-01 unemploy   8990
2865 2014-11-01 unemploy   9090
2866 2014-12-01 unemploy   8717
2867 2015-01-01 unemploy   8903
2868 2015-02-01 unemploy   8610
2869 2015-03-01 unemploy   8504
2870 2015-04-01 unemploy   8526

In [12]:
# tranformando o dataset de long para wide
data('economics_long')
head(economics_long)

  date       variable value value01
1 1967-07-01 pce      506.7 0.0000000000
2 1967-08-01 pce      509.8 0.0002652497
3 1967-09-01 pce      515.6 0.0007615234
4 1967-10-01 pce      512.2 0.0004706043
5 1967-11-01 pce      517.4 0.0009155394
6 1967-12-01 pce      525.1 0.0015743854

In [13]:
economics_long  %>% 
    select(-value01)  %>% 
    spread(variable, value, fill = NA)

    date       pce     pop      psavert uempmed unemploy
1   1967-07-01 506.7   198712   12.6    4.5     2944
2   1967-08-01 509.8   198911   12.6    4.7     2945
3   1967-09-01 515.6   199113   11.9    4.6     2958
4   1967-10-01 512.2   199311   12.9    4.9     3143
5   1967-11-01 517.4   199498   12.8    4.7     3066
6   1967-12-01 525.1   199657   11.8    4.8     3018
7   1968-01-01 530.9   199808   11.7    5.1     2878
8   1968-02-01 533.6   199920   12.3    4.5     3001
9   1968-03-01 544.3   200056   11.7    4.1     2877
10  1968-04-01 544.0   200208   12.3    4.6     2709
11  1968-05-01 549.8   200361   12.0    4.4     2740
12  1968-06-01 556.3   200536   11.7    4.4     2938
13  1968-07-01 563.2   200706   10.7    4.5     2883
14  1968-08-01 567.0   200898   10.5    4.2     2768
15  1968-09-01 568.2   201095   10.6    4.6     2686
16  1968-10-01 571.6   201290   10.8    4.8     2689
17  1968-11-01 576.7   201466   10.6    4.4     2715
18  1968-12-01 576.5   201621   11.1    4.4     2685
19  1969-01-01 583.5   201760   10.3    4.4     2718
20  1969-02-01 588.7   201881    9.7    4.9     2692
21  1969-03-01 588.9   202023   10.2    4.0     2712
22  1969-04-01 593.9   202161    9.7    4.0     2758
23  1969-05-01 600.3   202331   10.1    4.2     2713
24  1969-06-01 600.9   202507   11.1    4.4     2816
25  1969-07-01 602.7   202677   11.8    4.4     2868
26  1969-08-01 609.9   202877   11.5    4.4     2856
27  1969-09-01 613.2   203090   11.6    4.7     3040
28  1969-10-01 618.5   203302   11.4    4.5     3049
29  1969-11-01 620.5   203500   11.6    4.8     2856
30  1969-12-01 622.8   203675   11.8    4.6     2884
... ...        ...     ...      ...     ...     ...
545 2012-11-01 11136.8 315053.9  9.7    18.6    12005
546 2012-12-01 11140.5 315232.8 12.0    17.7    12298
547 2013-01-01 11202.8 315389.6  6.3    15.8    12471
548 2013-02-01 11239.6 315520.1  5.8    17.2    11950
549 2013-03-01 11227.1 315662.2  5.9    17.6    11689
550 2013-04-01 11205.4 315817.9  6.4    17.1    11760
551 2013-05-01 11244.6 315983.7  6.7    17.1    11654
552 2013-06-01 11268.8 316171.0  6.8    17.0    11751
553 2013-07-01 11296.7 316358.8  6.6    16.2    11335
554 2013-08-01 11329.2 316580.3  6.7    16.5    11279
555 2013-09-01 11366.9 316806.1  6.8    16.5    11270
556 2013-10-01 11419.8 317022.3  6.3    16.3    11136
557 2013-11-01 11487.6 317228.0  6.2    17.1    10787
558 2013-12-01 11517.9 317411.6  6.4    17.3    10404
559 2014-01-01 11512.5 317593.9  7.1    15.4    10202
560 2014-02-01 11566.2 317753.9  7.3    15.9    10349
561 2014-03-01 11643.0 317917.2  7.4    15.8    10380
562 2014-04-01 11702.6 318089.2  7.4    15.7     9702
563 2014-05-01 11748.4 318269.5  7.4    14.6     9859
564 2014-06-01 11817.0 318464.2  7.4    13.8     9460
565 2014-07-01 11860.5 318662.4  7.5    13.1     9608
566 2014-08-01 11944.3 318893.8  7.2    12.9     9599
567 2014-09-01 11957.4 319125.3  7.4    13.4     9262
568 2014-10-01 12023.0 319353.7  7.2    13.6     8990
569 2014-11-01 12051.4 319564.2  7.3    13.0     9090
570 2014-12-01 12062.0 319746.2  7.6    12.9     8717
571 2015-01-01 12046.0 319928.6  7.7    13.2     8903
572 2015-02-01 12082.4 320074.5  7.9    12.9     8610
573 2015-03-01 12158.3 320230.8  7.4    12.0     8504
574 2015-04-01 12193.8 320402.3  7.6    11.5     8526